config/routes.rb
Rails.application.routes.draw do
  # get 'homes/top'

  devise_for :users
  root to: 'homes#top'
  resources :books, only: [:new, :create, :index, :show, :destroy, :edit, :update]
  resources :users, only: [:show, :edit, :index, :update]
  get "home/about"=>"homes#about"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :body, presence: true







#   def new
#     @book = Book.new
#   end

#   # 投稿データの保存
#   def create
#     @book = PostImage.new(post_image_params)
#     @book.user_id = current_user.id
#     @book.save
#     redirect_to post_images_path
#   end

#   private

#   def post_image_params
#     params.require(:post_image).permit(:shop_name, :image, :caption)
#   end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :books, dependent: :destroy

  has_one_attached :profile_image
  
  validates :name, presence: true

  # def get_profile_image
  #   unless profile_image.attached?
  #     file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
  #     profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
  #   end
  #   profile_image.variant(resize_to_limit: [100, 100]).processed
  # end
  def get_profile_image(width, height)
    unless profile_image.attached?
     file_path = Rails.root.join('app/assets/images/default-image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
     profile_image.variant(resize_to_limit: [width, height]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end


  
  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user=current_user
      @books=Book.all
      render :index
      # @books=Book.all
      # # flash.now[:notice] = "Book was error create."
      # render :index
    end
  end

  def show
    @user=current_user
    @book = Book.find(params[:id])
  end

  def index
    @user=current_user
    @book=Book.new
    @books=Book.all
  end

  def edit
     @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])  # データ（レコード）を1件取得
    @book.destroy  # データ（レコード）を削除
    redirect_to '/books'  # 投稿一覧画面へリダイレクト
  end

   private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @book=Book.new
    @user=User.find(params[:id])
    @books=@user.books
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "Book was successfully created."
      redirect_to book_path(@book.id)
    else
      @user=current_user
      @books=Book.all
      render :index
    end
  end

  def index
    @user=current_user
    @book=Book.new
    @users=User.all
  end

  def new
  end

  def edit
   @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully created."
      redirect_to user_path(current_user.id)
    else
      @user = User.find(params[:id])
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/edit.html.erb
 <main>
        <p id="notice"></p>
        <div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	
<!--  		<form action="/books/139654" accept-charset="UTF-8" method="post"><input type="hidden" name="_method" value="patch" autocomplete="off" /><input type="hidden" name="authenticity_token" value="ioIqcgU9qAc0Ihm4RGnYXXsSsFz188-wuMA6_JXSiPzYHDNQg97XTo5JO7vb8tVmunXROzr6p_lKsBvqSNxyFw" autocomplete="off" />-->
<!--  <div class="form-group">-->
<!--    <label for="book_title">Title</label>-->
<!--    <input class="form-control book_title" type="text" value="ko" name="book[title]" id="book_title" />-->
<!--  </div>-->
<!--  <div class="form-group">-->
<!--    <label for="book_opinion">Opinion</label>-->
<!--    <textarea class="form-control book_body" name="book[body]" id="book_body">-->
<!--jkoo</textarea>-->
<!--  </div>-->
<!--  <div class="form-group">-->
<!--    <input type="submit" name="commit" value="Update Book" class="btn btn-success" data-disable-with="Update Book" />-->
<!--  </div>-->
<!--</form>-->
<!--  		<a class="book_139654" href="/books/139654">Show</a> |-->
<!--  		<a class="back" href="/books">Back</a>-->
<!--  </div>-->
<!--</div>-->
<!--      </main>-->
      
<%= form_with model: @book, url: book_path(@book.id), method: :patch do |f| %>

  <h4>Title</h4>
  <%= f.text_field :title, class: 'form-control' %>

  <h4>Opipnion</h4>
  <%= f.text_area :body, class: 'form-control' %><br>

  <%= f.submit 'Update Book', class: 'btn btn-success' %><br>

  <%= link_to "Show", book_path(@book.id) %>  |
  <a class="back" href="/books">Back</a>


<% end %>      

app/views/books/index.html.erb
index

<% if @book.errors.any? %>
  <%= @book.errors.count %>件のエラーが発生しました
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

</header>
      <main>
        <div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <table class='table'>



  <tr>
    <%= image_tag @user.get_profile_image(100, 100) %>
	  <th>name</th>
	  <th><%=@user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%=@user.introduction %></th>
  </tr>
</table>

<%= link_to  edit_user_path(current_user),class:"btn btn-outline-secondary btn-block " do %>
        <i class="fas fa-user-cog"></i>
        <% end %>
<!--<div class='row'>-->
<!--  <a class="btn btn-outline-secondary btn-block edit_user_177688" href="/users/177688/edit">-->
<!--    <i class="fas fa-user-cog"></i>-->
<!--</a></div>-->
      <h2 class="mt-3">New book</h2>
<%= form_with model: @book do |f| %>
<div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class: 'btn btn-success'%>
  </div>
<% end %>

    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
<table class='table table-hover table-inverse'>
   <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
<% @books.each do |book| %>
 <tr>
  <td>
    <%= image_tag @user.get_profile_image(90, 90) %>
  </td>
  <td>
    <%= link_to book_path(book.id) do %><%=book.title %>
    <% end %>
  </td>
  <td><%= book.body %>
     
    <!--<a data-confirm="本当に消しますか？" class="btn btn-sm btn-danger destroy_book_139533" rel="nofollow" data-method="delete" href="/books/139533">Destroy</a>-->
    </td>
  </tr>
<% end %>


  </tbody>
</table>
    </div>
  </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
show
<%= flash[:notice] %>
</header>
      <main>
        <div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <table class='table'>


  <tr>
    <%= image_tag @user.get_profile_image(100, 100) %>
	  <th>name</th>
	  <th><%=@user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%=@user.introduction %></th>
  </tr>
</table>

<%= link_to  edit_user_path(current_user),class:"btn btn-outline-secondary btn-block " do %>
        <i class="fas fa-user-cog"></i>
        <% end %>
<!--<div class='row'>-->
<!--  <a class="btn btn-outline-secondary btn-block edit_user_177688" href="/users/177688/edit">-->
<!--    <i class="fas fa-user-cog"></i>-->
<!--</a></div>-->
      <h2 class="mt-3">New book</h2>
<%= form_with model: @book do |f| %>
<div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class: 'btn btn-success'%>
  </div>
<% end %>

    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Book detail</h2>
<table class='table table-hover table-inverse'>

  <tbody>

  <tr>
  <td>
    <%= image_tag @user.get_profile_image(100, 100) %>
  </td>
  <td>
    <!--<%= link_to book_path(@book.id) do %><%= @book.title %>-->
    <!--<% end %>  -->
    <%= link_to @book.title, book_path(@book.id) %>
  </td>
  <td>
    <%=  @book.body %>
  </td>
  <td>
    <%= link_to  edit_book_path(@book.id),class:"btn btn-sm btn-success" do %>Edit
    <% end %>
  </td>
  <td>
    <% if @book.user == current_user %>
    　<%= link_to book_path, class:"btn btn-sm btn-danger", method: :delete, "data-confirm" => "本当に削しますか？" do %>Destroy
      <% end %>
    <% end %>

    <!--<a data-confirm="本当に消しますか？" class="btn btn-sm btn-danger destroy_book_139533" rel="nofollow" data-method="delete" href="/books/139533">Destroy</a>-->
  <!--  </td>-->
  </tr>

  </tbody>
</table>
    </div>
  </div>
</div>

app/views/homes/about.html.erb
<main>
        <p id="notice"></p>
        <div class='container'>
  <div class='row'>
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
  </div>
</div>
      </main>
    <footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

app/views/homes/top.html.erb
<!--<h1>Homes#top</h1>-->
<!--<p>Find me in app/views/homes/top.html.erb</p>-->


<!--<!DOCTYPE html>-->
<!--<html>-->
<!--  <head>-->
<!--    <title>Bookers2Ver2</title>-->
<!--    <meta name="csrf-param" content="authenticity_token" />-->
<!--<meta name="csrf-token" content="-wW0eHPzR38gvK0MkpNqDJzq2Be6KsJlpdIorVGA_mEkJpyZyiD3mqHX8Mmuu8nrGVdDczuruybqL6BN9yt4IQ" />-->
    
<!--    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">-->
<!--    <link rel="stylesheet" media="all" href="/packs/css/application-f5b9aaf7.css" data-turbolinks-track="reload" />-->
<!--    <script src="/packs/js/application-def8dd026df2759b5728.js" data-turbolinks-track="reload"></script>-->
<!--  </head>-->
<!--  <body>-->
<!--    <header>-->
<!--  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">-->
<!--    <div class="container">-->
<!--      <a class="navbar-brand" href="/"><span>Bookers</span></a>-->
<!--      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">-->
<!--        <span class="navbar-toggler-icon"></span>-->
<!--      </button>-->
<!--      <div class="collapse navbar-collapse" id="navbarNavDropdown">-->
<!--        <ul class="navbar-nav ml-auto">-->
<!--          <li>-->
<!--            <a class="nav-link text-light" href="/">-->
<!--              <i class="fa-solid fa-home"></i> Home-->
<!--</a>          </li>-->
<!--          <li>-->
<!--            <a class="nav-link text-light" href="/home/about">-->
<!--              <i class="fa-solid fa-link"></i> About-->
<!--</a>          </li>-->
<!--          <li>-->
<!--            <a class="nav-link text-light" href="/users/sign_up">-->
<!--              <i class="fa-solid fa-user-plus"></i> Sign up-->
<!--</a>          </li>-->
<!--          <li>-->
<!--            <a class="nav-link text-light" href="/users/sign_in">-->
<!--              <i class="fa-solid fa-sign-in-alt"></i> Log in-->
<!--</a>          </li>-->
<!--        </ul>-->
<!--      </div>-->
<!--    </div>-->
<!--  </nav>-->
<!--</header>-->
      <main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>
      <h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fa-solid fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>
        </div>
      </div>
    </div>
  </div>
</div>


      </main>
    <footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>CopyRight Infratop.inc</p>
    	</div>
    </div>
  </div>
</footer>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/3cd8f306bd.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>


  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>Bookers</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
    <% if user_signed_in? %>
      <li>
        <%= link_to  user_path(current_user),class:"nav-link text-light" do %>
        <i class="fa-solid fa-home"></i> Home
        <% end %>
      </li>
        <li>
        <%= link_to users_path,class:"nav-link text-light" do %>
        <i class="fa-solid fa-users"></i> Users
        <% end%>
      </li>
        <li>
        <%= link_to books_path,class:"nav-link text-light" do %>
        <i class="fa-solid fa-book-open"></i> Books
        <% end %>
      </li>
        <li>
        <%= link_to destroy_user_session_path, class:"nav-link text-light", method: :delete do %>
        <i class="fa-solid fa-sign-out-alt"></i> Log out
        <% end %>
      </li>
    <% else %>
      <li>
        <%= link_to  root_path,class:"nav-link text-light" do %>
        <i class="fa-solid fa-home"></i> Home
        <% end %>
      </li>
      <li>
        <%= link_to home_about_path,class:"nav-link text-light" do %>
        <i class="fa-solid fa-link"></i> About
        <% end %>
      </li>
        <li>
        <%= link_to new_user_registration_path,class:"nav-link text-light" do %>
        <i class="fa-solid fa-user-plus"></i> Sign up
        <% end %>
      </li>
      <li>
        <%= link_to new_user_session_path,class:"nav-link text-light" do %>
        <i class="fa-solid fa-sign-in-alt"></i> Log in
        <% end %>
      </li>
    <% end %>
<!--          <li>-->
<!--            <a class="nav-link text-light" href="/">-->
<!--              <i class="fa-solid fa-home"></i> Home-->
<!--</a>          </li>-->
<!--          <li>-->
<!--            <a class="nav-link text-light" href="/home/about">-->
<!--              <i class="fa-solid fa-link"></i> About-->
<!--</a>          </li>-->
<!--          <li>-->
<!--            <a class="nav-link text-light" href="/users/sign_up">-->
<!--              <i class="fa-solid fa-user-plus"></i> Sign up-->
<!--</a>          </li>-->
<!--          <li>-->
<!--            <a class="nav-link text-light" href="/users/sign_in">-->
<!--              <i class="fa-solid fa-sign-in-alt"></i> Log out-->
<!--</a>          </li>-->
        </ul>
      </div>
    </div>
  </nav>
</header>
<!--      <main>-->
<!--        <p id="notice"></p>-->
<!--        <div class="container">-->
<!--  <div class="row">-->
<!--    <div class='mx-auto col-11 col-sm-10 col-lg-8 col-xl-6'>-->
<!--      <h1>welcome to <i class="fa-solid fa-book"></i><strong>Bookers</strong>  !!</h1>-->
<!--      <p>In  <i class="fa-solid fa-book"></i><strong>Bookers</strong>, </p>-->
<!--      <p>you can share and exchange  your opinions , inpressions , and emotions</p>-->
<!--      <p> about various books!</p>-->
<!--      <div class="btn-wrapper col-10 mx-auto">-->
<!--        <div class="row">-->
<!--          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>-->
<!--        </div>-->
<!--        <div class="row">-->
<!--          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign up</a>-->
<!--        </div>-->
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->
<!--</div>-->


<!--      </main>-->
<!--    <footer>-->
<!--  <div class='container mt-5'>-->
<!--  	<div class='row'>-->
<!--    	<div class='mx-auto'>-->
<!--    		<p>CopyRight Infratop.inc</p>-->
<!--    	</div>-->
<!--    </div>-->
<!--  </div>-->
<!--</footer>-->

<!--  </body>-->
<!--</html>-->

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<main>
<% if @user.errors.any? %>
  <%= @user.errors.count %>件のエラーが発生しました
  <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

        <p id="notice"></p>
        <div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <!--<form enctype="multipart/form-data" action="/users/178092" accept-charset="UTF-8" method="post"><input type="hidden" name="_method" value="patch" autocomplete="off" /><input type="hidden" name="authenticity_token" value="46ZTcLPr38R1UlD7ZNZNG4Wflb8iC9qaDCflDkfJrT5CiATc7P0916Otg9YF6MF6hJUT3BGghLy75AIeBFGMCw" autocomplete="off" />-->
    <%= form_with model: @user do |f| %>
    <div class="form-group">
        <label for="user_name">Name</label>
        <%= f.text_field :name, class: 'form-control' %>
        <!--<input class="form-control name" type="text" value="孝太" name="user[name]" id="user_name" />-->
      </div>
     <div class="form-group">
        <label for="user_image">Image</label><br>
        <%= f.file_field :image, accept: "image/*" %>
        <!--<input class="form-control-file user_image" accept="image/*" type="file" name="user[profile_image]" id="user_profile_image" />-->
      </div>
      <div class="form-group">
        <label for="user_introduction">Introduction</label>
        <%= f.text_area :introduction, class: 'form-control' %>
        <!--<textarea class="form-control introduction" name="user[introduction]" id="user_introduction">-->
</textarea>
      </div>
      <div class="form-group">
        <%= f.submit 'Update User', class: 'btn btn-secondary'%>
        <!--<input type="submit" name="commit" value="Update User" class="btn btn-secondary" data-disable-with="Update User" />-->
      </div>
      <% end %>


</form>  </div>
</div>

      </main>

app/views/users/index.html.erb
index
<%= flash[:notice] %>
</header>
      <main>
        <div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <table class='table'>



  <tr>
    <%= image_tag @user.get_profile_image(100, 100) %>
	  <th>name</th>
	  <th><%=@user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%=@user.introduction %></th>
  </tr>
</table>

<%= link_to  edit_user_path(current_user),class:"btn btn-outline-secondary btn-block " do %>
        <i class="fas fa-user-cog"></i>
        <% end %>
<!--<div class='row'>-->
<!--  <a class="btn btn-outline-secondary btn-block edit_user_177688" href="/users/177688/edit">-->
<!--    <i class="fas fa-user-cog"></i>-->
<!--</a></div>-->
      <h2 class="mt-3">New book</h2>
<%= form_with model: @book do |f| %>
<div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class: 'btn btn-success'%>
  </div>
<% end %>

    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
     <% @users.each do |user| %>
  <tr>
  <td>
     <%= image_tag @user.get_profile_image(90, 90) %>
  </td>
  <td>
    <%=  user.name %>
  </td>
  <td>
    <%= link_to user_path(user.id) do%>Show
        <% end %>
  </tr>
  <% end %>
  </tbody>
</table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
show

<div>
   <%= flash[:notice] %>
</div>

</header>
      <main>
        <div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <table class='table'>



  <tr>
    <%= image_tag @user.get_profile_image(100, 100) %>
	  <th>name</th>
	  <th><%=@user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%=@user.introduction %></th>
  </tr>
</table>

<%= link_to  edit_user_path(current_user),class:"btn btn-outline-secondary btn-block " do %>
        <i class="fas fa-user-cog"></i>
        <% end %>
<!--<div class='row'>-->
<!--  <a class="btn btn-outline-secondary btn-block edit_user_177688" href="/users/177688/edit">-->
<!--    <i class="fas fa-user-cog"></i>-->
<!--</a></div>-->
      <h2 class="mt-3">New book</h2>
<%= form_with model: @book do |f| %>
<div class="form-group">
    <label for="book_title">Title</label>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="form-group">
    <label for="book_opinion">Opinion</label>
    <%= f.text_area :body, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit 'Create Book', class: 'btn btn-success'%>
  </div>
<% end %>

    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
     <% @books.each do |book| %>
  <tr>
  <td>
    <%= image_tag @user.get_profile_image(100, 100) %>  
  </td>
  <td>
    <%= link_to book_path(book.id) do %><%= book.title %>
    <% end %>  
  </td>
  <td>
    <%=  book.body %>
  </td>
  <!--<td>-->
  <!--  <%= link_to  edit_book_path(current_user),class:"btn btn-sm btn-success" do %>Edit-->
  <!--      <% end %>-->
  <!--</td>-->
  <!--<td>-->
  <!--  <%= link_to book_path(book.id), class:"btn btn-sm btn-danger", method: :delete do %>Destroy-->
  <!--      <% end %>-->
  <!--</tr>-->
  <% end %>
  </tbody>
</table>
    </div>
  </div>
</div>